# Generated by Django 2.2.6 on 2019-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedidos', '0003_delete_itensdospedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensDosPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=11)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
                ('id_produto', models.ManyToManyField(to='produtos.Produto')),
            ],
        ),
    ]
