# Generated by Django 2.2.6 on 2019-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itensdopedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensdospedidos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
