# Generated by Django 2.2.6 on 2019-11-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itensdopedido', '0003_auto_20191123_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensdospedidos',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
        ),
    ]
