# Generated by Django 2.2.6 on 2019-11-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('itensdopedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdospedidos',
            name='id_produto',
        ),
        migrations.AddField(
            model_name='itensdospedidos',
            name='id_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
            preserve_default=False,
        ),
    ]
