# Generated by Django 2.2.6 on 2019-11-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_id_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_produto',
        ),
    ]
